version: '3'

services:
  db:
    image: postgres:9.6
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    restart: always
    user: root
  api:
    build: 
      context: ./codetalk_api/
      dockerfile: Dockerfile
    command: /bin/sh -c "rm -f /myapp/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    image: rails:dev
    volumes:
      - ./codetalk_api:/myapp
      - ./codetalk_api/vendor/bundle:/myapp/vendor/bundle
    environment:
      TZ: Asia/Tokyo
      RAILS_ENV: development
      EDITOR: vi
    ports:
      - 3000:3000
    depends_on:
      - db
  front:
    build: 
      context: ./codetalk_front/
      dockerfile: Dockerfile
    volumes:
      - './codetalk_front:/app'
      - '/app/node_modules'
    ports:
      - "8000:8080"
  pgweb:
    image: sosedoff/pgweb
    container_name: "pgweb"
    ports:
      - "8081:8081"
    depends_on:
      - db
volumes:
  postgres-data:
    driver: local